#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2009 OpenCFD Ltd.
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     AllwmakeLibccmio
#
# Description
#     Get and build CD-adapco's ccmio library
#
#------------------------------------------------------------------------------
packageDir=libccmio-2.6.1
tarFile=$packageDir.tar.gz
url="https://wci.llnl.gov/codes/visit/3rd_party/$tarFile"

# run from third-party directory only
[ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit 1
. $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions

# get tar.gz file if required
if [ ! -d ${packageDir} ]
then
    downloadFile $tarFile $url

    if [ -e download/$tarFile ]
    then
        echo "unpack download/$tarFile"
        tar -xzf download/$tarFile
    else
        echo "no download/$tarFile to unpack"
    fi
fi

set -x

# make libccmio
(
    cd $packageDir || exit 1
    cpMakeFiles libccmio

    wmake libso
)


# ----------------------------------------------------------------- end-of-file
