#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2009 OpenCFD Ltd.
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     makeGcc
#
# Description
#     Build script for gmp, mpfr and gcc-4.3.? and gcc-4.4.?
#
#------------------------------------------------------------------------------

gmpPACKAGE=gmp-4.2.4
mpfrPACKAGE=mpfr-2.4.1
gccPACKAGE="$1"


# run from third-party directory only
[ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit
. $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions

#------------------------------------------------------------------------------
usage() {
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} <gcc-4.?.?> ...

* build gmp, mpfr and gcc-4.3.? and gcc-4.4.?

USAGE
    exit 1
}

[ "$#" -eq 1 ] || usage "gcc version not provided"

case "$1" in
-h | -help)
    usage
    ;;
esac


# get the number of cores to build on
getNCOMPPROCS verbose


GCC_ARCH_PATH=$WM_THIRD_PARTY_DIR/$gccPACKAGE/platforms/$WM_ARCH$WM_COMPILER_ARCH
GMP_ARCH_PATH=$WM_THIRD_PARTY_DIR/$gmpPACKAGE/platforms/$WM_ARCH$WM_COMPILER_ARCH
MPFR_ARCH_PATH=$WM_THIRD_PARTY_DIR/$mpfrPACKAGE/platforms/$WM_ARCH$WM_COMPILER_ARCH

#
# Bulid GMP
#
if [ -d $GMP_ARCH_PATH ]
else
    echo "Already built: $gmpPACKAGE"
else
(
    cd $gmpPACKAGE || exit
    make distclean
    mkdir build
    cd build

    ../configure ABI=$ABI --prefix=$GMP_ARCH_PATH \
    && make -j $WM_NCOMPPROCS \
    && make install

    echo "Built: $gmpPACKAGE"
)
fi

export LD_LIBRARY_PATH="$GMP_ARCH_PATH/lib:$LD_LIBRARY_PATH"

#
# Build MPFR
#
if [ -d $MPFR_ARCH_PATH ]
then
    echo "Already built: $mpfrPACKAGE"
else
(
    cd $mpfrPACKAGE || exit
    make distclean
    mkdir build
    cd build

    ../configure ABI=$ABI --prefix=$MPFR_ARCH_PATH --with-gmp=$GMP_ARCH_PATH \
    && make -j $WM_NCOMPPROCS \
    && make install

    echo "Built: $mpfrPACKAGE"
)
fi

export LD_LIBRARY_PATH="$MPFR_ARCH_PATH/lib:$LD_LIBRARY_PATH"

#
# Build GCC
#
if [ -d $GCC_ARCH_PATH ]
then
    echo "Already built: $gccPACKAGE"
else
(
    cd $gccPACKAGE || exit
    make distclean
    mkdir build
    cd build

    ../configure --prefix=$GCC_ARCH_PATH \
        --enable-languages=c,c++ --with-pkgversion='OpenFOAM' \
        --enable-__cxa_atexit --enable-libstdcxx-allocator=new \
        --with-system-zlib \
        --with-gmp=$GMP_ARCH_PATH --with-mpfr=$MPFR_ARCH_PATH \
    && make -j $WM_NCOMPPROCS \
    && make install

    echo "Built: $gccPACKAGE"
)
fi


# ----------------------------------------------------------------- end-of-file
