#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2010 OpenCFD Ltd.
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software: you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.
#
# Script
#     makeQt
#
# Description
#     Build script for qt-everywhere-opensource-src
#
#------------------------------------------------------------------------------
qtVERSION=4.6.2
qtTYPE=qt-everywhere-opensource-src
#------------------------------------------------------------------------------
# run from third-party directory only
wmakeCheckPwd "$WM_THIRD_PARTY_DIR" || {
    echo "Error: Current directory is not \$WM_THIRD_PARTY_DIR"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}
. tools/makeThirdPartyFunctions
#------------------------------------------------------------------------------

usage() {
    exec 1>&2
    while [ "$#" -ge 1 ]; do echo "$1"; shift; done
    cat<<USAGE

usage: ${0##*/} [VERSION]

* build $qtTYPE, version $qtVERSION

USAGE
    exit 1
}


# parse options
while [ "$#" -gt 0 ]
do
    case "$1" in
    -h | -help)
        usage
        ;;
    [1-9]*)
        qtVERSION="${1%%/}"
        shift
        ;;
    *)
        usage "unknown option/argument: '$*'"
        ;;
    esac
done

#------------------------------------------------------------------------------

# get the number of cores to build on
getNCOMPPROCS

qtPACKAGE=$qtTYPE-$qtVERSION
prefixDIR=$installBASE/qt-$qtVERSION

#
# Build QT
#
echo "---------------"
if [ -d "$prefixDIR" -a -r "$prefixDIR/bin/qmake" ]
then
    echo "Already built: Qt-$qtVERSION"
else
    echo "Starting build: Qt-$qtVERSION"
(
    cd $qtPACKAGE || exit 1

    make distclean 2>/dev/null
    rm -rf $prefixDIR

    # compile as opensource, accepting LGPL conditions
    echo "yes" | \
    ./configure \
        --prefix=$prefixDIR \
        -opensource \
        -nomake demos \
        -nomake examples \
    && time make -j $WM_NCOMPPROCS \
    && make install \
    && echo "Built: Qt-$qtVERSION"
) || {
    echo "Error building: Qt-$qtVERSION"
    exit 1
}
fi

# ----------------------------------------------------------------- end-of-file
