#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2009 OpenCFD Ltd.
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     makeQt
#
# Description
#     Build script for Qt-4.3.5
#
#------------------------------------------------------------------------------

QT_VERSION=4.3.5
QT_HOME=$WM_THIRD_PARTY_DIR/qt-x11-opensource-src-$QT_VERSION
QT_ARCH_PATH=$QT_HOME/platforms/$WM_OPTIONS

# run from third-party directory only
[ -d "$WM_THIRD_PARTY_DIR" ] && cd $WM_THIRD_PARTY_DIR || exit
. $WM_THIRD_PARTY_DIR/tools/makeThirdPartyFunctions

# get the number of cores to build on
getNCOMPPROCS


if [ -d "$QT_ARCH_PATH" ]
then
    echo "Already built: Qt-$QT_VERSION"
else
    echo "Starting build: Qt-$QT_VERSION"
(
    cd $QT_HOME || exit

    make distclean
    rm -rf $QT_ARCH_PATH

    ./configure --prefix=$QT_ARCH_PATH \
        -nomake demos \
        -nomake examples \
    && time make -j $WM_NCOMPPROCS \
    && make install \
    && echo "Built: Qt-$QT_VERSION"
) || {
    echo "Error building: Qt-$QT_VERSION"
    exit
}
fi

# ----------------------------------------------------------------- end-of-file
