#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libo fbsdmalloc
# wmake libo bsdmalloc
# wmake libo gmalloc
# wmake libo mmalloc
# wmake libo g++malloc

# ----------------------------------------------------------------- end-of-file
